### ISSUE TITLE
Feat: Use Factory patter and add more tests

### ISSUE THREAD

**Issue by codebuster22** [njokuScript/base-migrate#12]
Current Smart Contracts package lacks test and no factory exist to deploy new tokens easily without compiling the contract and deploying it.

**Describe the solution you'd like**
When new tokens will be bridged they will have standard contract. To make it easier for the frontend, gas-efficient and indexable, a factory pattern is recommended. Using factory pattern, the dapp can deploy new contract using one function call.

Add more tests.

**Describe alternatives you've considered**
The above mentioned solution is a standard approach for bridges, also implemented by Optimism.

**Additional context**
I have made the fix, then realized the whole repo have been restructured, hence, now I have created another branch with the solution.

**Comment by njokuScript** [comment]
Thanks for your contribution! will review the pr now!

**Comment by njokuScript** [comment]
@codebuster22 Can you add deployment scripts for foundry(forge script) since we are not using Hardhat anymore?

**Comment by codebuster22** [comment]
Adding deploy script now.

**Comment by codebuster22** [comment]
Created a PR.
@njokuScript
